// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6PeFH6soFKiqWgQ2bycv9aWzfUKPBXOY',
    appId: '1:908391948877:web:9a63adf49459ddb4ee3204',
    messagingSenderId: '908391948877',
    projectId: 'walltutorial-1dfc8',
    authDomain: 'walltutorial-1dfc8.firebaseapp.com',
    storageBucket: 'walltutorial-1dfc8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR8xdhzYBnswOg6LM21eFl1BJ-iOE-nFc',
    appId: '1:908391948877:android:cea8d4f3b70dc8f6ee3204',
    messagingSenderId: '908391948877',
    projectId: 'walltutorial-1dfc8',
    storageBucket: 'walltutorial-1dfc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYibIXszQnlzb5VJKbxGPYxtOX_EDkds',
    appId: '1:908391948877:ios:f1b2bb3563e0311cee3204',
    messagingSenderId: '908391948877',
    projectId: 'walltutorial-1dfc8',
    storageBucket: 'walltutorial-1dfc8.appspot.com',
    iosClientId: '908391948877-tq07tv4bgutqjjocogkag0fheriv4s3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.medaka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpYibIXszQnlzb5VJKbxGPYxtOX_EDkds',
    appId: '1:908391948877:ios:62812f1ad98098d9ee3204',
    messagingSenderId: '908391948877',
    projectId: 'walltutorial-1dfc8',
    storageBucket: 'walltutorial-1dfc8.appspot.com',
    iosClientId: '908391948877-mnp5ba9iue2sspboet2pvorofrv0kou6.apps.googleusercontent.com',
    iosBundleId: 'com.example.medaka.RunnerTests',
  );
}
